# Site settings
title: Lend-A-Hand
email: hello@coderocket.me
description: > OpenSource Job Board written in
Ruby on Rails to help finding Open Source projects
which needs a helping hand or two...
url: http://dominicrico.github.io
baseurl: /lend-a-hand
twitter_username: coderocket_
github_username:  dominicrico

# Build settings
markdown: kramdown
